### PR TITLE
More refactoring of the pin functionality

### LINKED ISSUE #56: Symbols get messed up with multiple selections
Using symbols to display categorical data interferes with selection highlighting, particularly when using multiple structure panels.

Expected behavior:
Highlighted structures are shown using the same symbol used for the category, which is just made a bit bigger and colored according to the structure panel color key. 

Observed behavior:
in 2D, a circle is used regardless of the underlying class
in 3D (even more problematic) the symbol of the active panel is used for all the selected structures (so that a structure with a square symbol might turn into a cross if I select a cross structure as the active one)

Might be linked to #50  and #11

### PR DESCRIPTION
**Pull request by Luthaf**
Fix #56 

Continue working on #45: all of the communication between map & viewer grid now happen through public method & callback (no `getById`); and there are separated callback/methods for 

- adding a new pinned environment; 
- removing a pinned environment; 
- changing which pinned environment is the active one
- changing which environment is showed by the active viewer

All these methods exists on the viewer side, while the map only exposes the "change which env is showed" & "change the active viewer" since that's all the user can do with the map.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -129,58 +130,55 @@ class DefaultVisualizer {
...
-        );
-
-        this.map.active = this.structure.active;
-
         if (config.loadStructure !== undefined) {
             this.structure.loadStructure = config.loadStructure;
         }
 
+        this.structure.activeChanged = (guid, indexes) => {
+            this.map.setActive(guid);
```
Comment (rosecers) [inline src/index.ts:138]: Is it kosher to set up these actions wrt the map before initializing said map?

File: src/map/map.ts [hunk 2]
```diff
@@ -198,12 +201,15 @@ interface MarkerData {
  * plot markers.
  */
 export class PropertiesMap {
-    /** Callback fired when the plot is clicked and a new point is selected */
+    /** Callback fired when the plot is clicked and the position of the active marker changes */
     public onselect: (indexes: Indexes) => void;
-    /** Callback fired when a guid is removed from the map */
-    public onremove: (removedGUID: string) => void;
```
Comment (rosecers) [inline src/map/map.ts:204]: Why have you removed the `onremove` call? Now under 3D the deleted widgets still remain as markers on the 3D map, so I'm assuming the removal of widgets is no longer effectively communica
Screen Shot 2020-07-06 at 11 23 36 AM
ted.

Comment (rosecers) [reply src/map/map.ts:204]: Also, after the marker is not removed, the activating of markers on the right does not correspond with the markers 
Screen Shot 2020-07-06 at 11 25 27 AM
on the right.

File: src/map/map.ts [hunk 3]
```diff
@@ -347,92 +313,114 @@ export class PropertiesMap {
...
-     * @param  activeGUID the GUID of the new active viewer
+     * @param guid the GUID of the new active viewer
      */
-    public set active(activeGUID: string) {
-        if (this._active === activeGUID) {
-            // guard against infinite recursion
-            // `Structure set active => StructureViewer.show => Map set active
-            // => PropertiesMap.select => Structure set active`
-            return;
+    public setActive(guid: GUID) {
```
Comment (rosecers) [inline src/map/map.ts:343]: Why did you change from the `set active` style?

File: src/map/map.ts [hunk 4]
```diff
@@ -347,92 +313,114 @@ export class PropertiesMap {
...
-            this._active = activeGUID;
-            newButton.classList.toggle('chsp-active-structure', true);
+    /**
+     * Add a new marker to the map. The new marker is set as the active one
+     *
+     * @param guid GUID of the new marker
+     * @param indexes indexes of the environment that the new marker should show
+     */
+    public addMarker(guid: GUID, color: string, indexes: Indexes): void {
+        assert(!this._selected.has(guid));
```
Comment (rosecers) [inline src/map/map.ts:367]: Why do we need this assertion?

File: src/index.ts (hunk 1 above)
Comment (Luthaf) [reply src/index.ts:138]: Since the callback will not be called before everything is initialized, I don't see this as a problem. I find the code easier to follow if everything related to the structure is close together

File: src/map/map.ts (hunk 2 above)
Comment (Luthaf) [reply src/map/map.ts:204]: > Why have you removed the onremove call?

Because the map can never initiate marker removal, and all the callbacks are used to transmit actions from the users on a given panel to all others panels. 

I'll look into the bugs you've found!

File: src/map/map.ts (hunk 3 above)
Comment (Luthaf) [reply src/map/map.ts:343]: For two reason: we sometimes want to use `this._active = '...'` and sometimes `this.active = '...'`. Having a setter instead of a function make the code confusing, since you have to remember the difference. It also allow to follow the same style as the rest of the actions on the map/structure grid: `map.setActive(...)`, `map.select(...)`, etc.

File: src/map/map.ts (hunk 4 above)
Comment (Luthaf) [reply src/map/map.ts:367]: To ensure we don't add the same marker multiple times

File: src/index.ts (hunk 1 above)
Comment (rosecers) [reply src/index.ts:138]: I don't disagree, but it is a bit disconcerting to write operations on things that don't yet exist.

File: src/map/map.ts (hunk 4 above)
Comment (rosecers) [reply src/map/map.ts:367]: I'm often more in favor of quitting the function than throwing an error, but that's most likely a style choice.

File: src/map/map.ts (hunk 2 above)
Comment (rosecers) [reply src/map/map.ts:204]: I strongly think we should retain a shadow functionality to remove from the map, it may be something we want to have in the future (happy to discuss in the future)

File: src/map/map.ts (hunk 4 above)
Comment (Luthaf) [reply src/map/map.ts:367]: The issue with quitting the function is that it can hide programming errors since it fails silently. I try to use [defensive programming](https://en.wikipedia.org/wiki/Defensive_programming) and fail as early as possible to catch control flow errors & other issues

File: src/map/map.ts (hunk 2 above)
Comment (Luthaf) [reply src/map/map.ts:204]: > shadow functionality to remove from the map,

What do you mean by shadow functionality?

Comment (Luthaf) [reply src/map/map.ts:204]: And if this is something we may want to have in the future, then we can implement it in the future =) But since there is no use case for it now, I would rather keep the code as simple as possible, since that makes future modification easier

Comment (Luthaf) [reply src/map/map.ts:204]: Regarding the bugs, the `Map.removeMarker` was missing `if (this._is3D()) {this._updateAll3DMarkers();}`, everything should work now.

**Comment by ceriottm** [comment]
Possibly related to this effort: in the master, if you change the selected structure on the structure panel, the info panel is not updated.

**Comment by Luthaf** [comment]
> Possibly related to this effort: in the master, if you change the selected structure on the structure panel, the info panel is not updated. Might relate to Rose's question on whether the link should be one-sided or not.

That's fixed with this branch, as a side effect of separating "change the active viewer" from "change what the active viewer shows"

----

I am not sure I understand what you mean with one-sided relationship here: that only the structure can create/remove pinned viewer? That is by design since there is no UI to add/remove markers on the map side. Or are you referring to something else?

**Comment by ceriottm** [comment]
> > Possibly related to this effort: in the master, if you change the selected structure on the structure panel, the info panel is not updated. Might relate to Rose's question on whether the link should be one-sided or not.
> 
> That's fixed with this branch, as a side effect of separating "change the active viewer" from "change what the active viewer shows"
> 
> I am not sure I understand what you mean with one-sided relationship here: that only the structure can create/remove pinned viewer? That is by design since there is no UI to add/remove markers on the map side. Or are you referring to something else?

OK great - no I didn't undertand the issue either apparently so if this fixes it, all good and many thumbs up

**Comment by Luthaf** [comment]
> such as using setActive instead of set active, even though I get why

I kinda like seeing entity objects in the Smalltalk sense, i.e. objects are actors that communicate with one another by passing messages (calling methods from other objects, or reacting with callbacks). 

This is also related to the entity class vs value class distinction (I've mostly seen this distinction in C++ land): entity class are full actors, that maintain internal invariant and communicate with methods. Value classes are bags of data that mostly don't have any invariant and 'just' store multiple fields together. For classes with value semantics, getter/setters make more sense, since they make the code look like an actual bag of value, even if we need some internal checks.

The easiest way to see if a class have value or entity semantics is to check if two instances with the same members values have the same identity. Two `StructureGrid` would be different and behave differently here; but two `strings` with the same content would be completely interchangeable.

A bit of reading on the subject if you are interested =)

https://akrzemi1.wordpress.com/2012/02/03/value-semantics/
https://softwareengineering.stackexchange.com/questions/408540/value-reference-type-object-and-semantics
